### ISSUE TITLE
Swapping tags doesn't work

### ISSUE THREAD

**Issue by frioux** [XLegion/sharetags#2]
Not sure if this is the fault of this library or my integration with it.  Basically, if I try to swap tags (ie while tag 2 and 3 are both visible, and I press mod+2 while tag 3 is the current tag) the old tag disappears and the screen that had it just goes blank.

The code I'm using to swap is:

```
        awful.key({ modkey }, "#" .. i + 9,
                  function ()
                        local t = tags[i]
                        local swap_t = awful.tag.selected()
                        local swap_s = t.screen
                        local sel = t.selected
                        if t.screen ~= mouse.screen then
                            sharetags.tag_move(t, mouse.screen)
                        end
                        if sel == true then
                            sharetags.tag_move(swap_t, swap_s)
                            awful.tag.viewonly(swap_t)
                        end
                        awful.tag.viewonly(t)
                  end),
```

I'm going to try to fiddle with that code and see if I can fix it there, but it worked before I switched to this (and awesome 3.5)

**Comment by frioux** [comment]
All the tweaks I tried there did nothing.

**Comment by solodkiy** [comment]
You can bind sharetags.swap_screen function on any key 
`function swap_screen(screen1, screen2)`
or uncomment code on 123 line init.lua
but probably you get errors with lost window focus

**Comment by frioux** [comment]
I stopped using this.
